// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aresikejzipyhaxicbfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZXNpa2VqemlweWhheGljYmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjA1MjcsImV4cCI6MjA3MjEzNjUyN30.n3zqmndqTTEQ-u1dNdQ0VBWV3EtsQLYGfo1DxGBL0cw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});